### ISSUE TITLE
Call to a member function getCode() on null

### ISSUE THREAD

**Issue by mtaita** [antonioribeiro/tracker#250]
Hi all,
I have installed laravel stats tracker on laravel 5.4.*  but when i run php artisan migrate i get the following error

C:\wamp\www\dihabuka>php artisan migrate
Migration table created successfully.

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getCode() on null

Please any Idea on this help me

**Comment by leviko97** [comment]
I've got the same problem

**Comment by antonioribeiro** [comment]
Tagged 0.6.15, should be fixed now. Please report back.

**Comment by mtaita** [comment]
Yes it is ok but still getting this new error
I have tried your suggestions on #249 but not fixed yet
![tracker](https://cloud.githubusercontent.com/assets/20210957/23257566/7deb410c-f9d5-11e6-8f8f-01722d8eb063.PNG)

**Comment by kiwina** [comment]
$this->tracker->handleException($exception, $exception->getCode());

needs to be updated to
$this->tracker->handleException($exception);

**Comment by vesper8** [comment]
@antonioribeiro Hi Antonio! Your package sounds really powerful, but right now many of us can't install it because of issues with Laravel 5.4 and migrations. You say you fixed the problem here
```
Tagged 0.6.15, should be fixed now. Please report back.
```

Sorry.. I've been using Github for years but I am lost as to what you mean by this? The last commit I see on this package is dated Feb 5th.. and I don't see any tags with a more recent commit or any tag that resemble the 0.6.15 numbering. I don't see a develop or dev branch either.. what am I missing?

Also as mentioned in #249 there are other issues related to the migrations.. some users have offered advice on how to fix but so far I haven't been lucky getting it to work even after I set my tracker database strict => false

I think as you mentioned the migration files need to be cleaned up a bit so that this package can install normally on a new installation of Laravel 5.4

Is there any chance you could fix it and post a new release?

I would also really love to understand what you meant by "Tagged 0.6.15, should be fixed now" because I feel like there's an important part of how Github works that I don't understand right now.

Many thanks! Hope to use your package very soon!
