### ISSUE TITLE
Database Migrate not working with Laravel 5.6

### ISSUE THREAD

**Issue by ipulrvs** [antonioribeiro/tracker#379]
I got this error i follow all step, digging issue to solve the problem until i stuck with this :

Illuminate\Database\QueryException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myapp.tracker_query_arguments' doesn't exist (SQL: alter table `tracker_query_arguments` add constraint `tracker_query_arguments_query_id_foreign` foreign key (`query_id`) references `tracker_queries` (`id`) on delete cascade on update cascade)")
      D:\Workspace\My App\lanscareshop\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 664

Please help,

First time using Laravel with version 5.6, which version of laravel completely stable for using this repository ?

**Comment by houseofcoder** [comment]
Try migrating Trackers logging tables again..

**Comment by antonioribeiro** [comment]
Should be fixed on PHP 5.6 now.

**Comment by VardanBhanot** [comment]
Sir same error still prevails now, I am Also facing same error if you could do something

**Comment by Nowi5** [comment]
@VardanBhanot Please show your composer.json and check php version php -v.

**Comment by VardanBhanot** [comment]
@Nowi5  My PHP version is 7.1.9
And composer.json file is

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "pragmarx/tracker": "^3.3",
        "predis/predis": "^1.1",
        "spatie/laravel-activitylog": "^2.5",
        "spatie/laravel-permission": "^2.29",
        "summernote/summernote": "^0.8.8",
        "unisharp/laravel-ckeditor": "^4.7"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`
