### ISSUE TITLE
Erorr in events page 

### ISSUE THREAD

**Issue by Si-HaMaDa** [antonioribeiro/tracker#417]
I installed the pakage and worked fine but when trying to open events page in stats it's giving me error
pop up error:
DataTables warning: table id=table_div - Ajax error. For more information about this error, please see http://datatables.net/tn/7
and when trying to see the requests
here's the Request URL
http://localhost/saraha/public/stats/api/events?draw=1&columns[0][data]=name&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=total&columns[1][name]=&columns[1][searchable]=false&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=0&length=10&search[value]=&search[regex]=false&_=1547915504921

and here's the response

message | SQLSTATE[HY000]:  General error: 1 ambiguous column name: id (SQL: select  "tracker_events"."id", "tracker_events"."name",  count(tracker_events_log.id) as total from "tracker_events" inner join  "tracker_events_log" on "tracker_events_log"."event_id" =  "tracker_events"."id" where "tracker_events_log"."updated_at" >=  2019-01-18 16:31:47 and "tracker_events_log"."updated_at" <=  2019-01-19 16:31:47 group by "tracker_events"."id",  "tracker_events"."name" order by "total" desc, "id" asc limit 10 offset  0)
exception | Illuminate\Database\QueryException

**Comment by Si-HaMaDa** [comment]
http://localhost/saraha/public/stats/api/visits?draw=1&columns[0][data]=id&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=client_ip&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=country&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=true&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=user&columns[3][name]=&columns[3][searchable]=true&columns[3][orderable]=true&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=device&columns[4][name]=&columns[4][searchable]=true&columns[4][orderable]=true&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=browser&columns[5][name]=&columns[5][searchable]=true&columns[5][orderable]=true&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=language&columns[6][name]=&columns[6][searchable]=true&columns[6][orderable]=true&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=referer&columns[7][name]=&columns[7][searchable]=true&columns[7][orderable]=true&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=pageViews&columns[8][name]=&columns[8][searchable]=true&columns[8][orderable]=true&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=lastActivity&columns[9][name]=&columns[9][searchable]=true&columns[9][orderable]=true&columns[9][search][value]=&columns[9][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=0&length=10&search[value]=&search[regex]=false&_=1547915629809

**Comment by napestershine** [comment]
@Si-HaMaDa  can you please try now, after doing `composer update` ?

**Comment by Si-HaMaDa** [comment]
@napestershine 
for sorry still the same error

**Comment by napestershine** [comment]
@Si-HaMaDa  if possible can you attach a screenshot, I remember I fixed it last weekend And can't get same error on my system .

**Comment by Si-HaMaDa** [comment]
@napestershine 
Sorry for late but still the same problem in events page...
But this update fixed another problem which to fix I commented this
parent::__construct($attributes);
on line 16 in the construct in Base.php
now it's working fine without commenting this line

**Comment by antonioribeiro** [comment]
@Si-HaMaDa , Jus tagged a version 3.3.2, would you please update and try again?

**Comment by Si-HaMaDa** [comment]
@antonioribeiro
the same...
are you sure it's fixed?!
maybe I've something wrong!

**Comment by napestershine** [comment]
@Si-HaMaDa do you get same error message or it's different ?

**Comment by napestershine** [comment]
@Si-HaMaDa I am on it. I got it. I will push update in sometime.

**Comment by napestershine** [comment]
@Si-HaMaDa I have same system running, and same query is running on my system perfectly. Can you share system environment?

**Comment by Si-HaMaDa** [comment]
@napestershine 
I just tried to work with MySql and there's no error :D
so this error only happening with SqLite, I've tried on local and server and the error is the same when using SqLite
I mentioned in the first comment that I use SqLite, don't know if you see and try that or not :D

**Comment by RaymondSalim** [comment]
I know this is a pretty old thread, came across this too. Same as @Si-HaMaDa, I only got this error when using Sqlite.

I traced the error and it ends up being inside Datatables.php

```diff
// vendor/pragmarx/datatables/src/Bllim/Datatables/Datatables.php

.....

protected function ordering()
    {
        if (array_key_exists('order', $this->input) && count($this->input['order']) > 0) {
-            $columns = $this->cleanColumns($this->aliased_ordered_columns);
//            The "ambiguous column name" error is because $columns contains only the column name, while we need the table name
+            $columns = $this->aliased_ordered_columns;
            for ($i = 0, $c = count($this->input['order']); $i < $c; $i++) {
                $order_col = (int)$this->input['order'][$i]['column'];
                if (isset($columns[$order_col])) {
                    if ($this->input['columns'][$order_col]['orderable'] == "true") {
                        $this->query->orderBy($columns[$order_col], $this->input['order'][$i]['dir']);
                    }
                }
            }

        }
    }

....
```

After changing that it works now.
