### ISSUE TITLE
Error: vendor/pragmarx/datatables/src/Bllim/Datatables/views" directory does not exist

### ISSUE THREAD

**Issue by khoazero123** [antonioribeiro/tracker#456]
**Describe the bug**

**To Reproduce**
Run command: php artisan view:cache

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2802354/63143885-a9aed200-c01a-11e9-894c-bb2bc5b6016b.png)

**System**
 - OS: Ubuntu
 - Browser: command line
 - Version: Laravel 5.8, pragmarx/tracker: 3.3

**Additional context**

**Comment by drbyte** [comment]
Related: #452, #431

**Comment by antonioribeiro** [comment]
Should be fixed now.

**Comment by tornadofay** [comment]
I'm sorry to reopen this but i still have this error

> C:\wamp\www\SPF>php artisan view:cache
> Compiled views cleared!
> 
>    Symfony\Component\Finder\Exception\DirectoryNotFoundException  : The "C:\wamp\www\SPF\vendor\pragmarx\datatables\src\Bllim\Datatables/views" directory does not exist.
> 
>   at C:\wamp\www\SPF\vendor\symfony\finder\Finder.php:601
>     597|                 $resolvedDirs[] = $this->normalizeDir($dir);
>     598|             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? GLOB_BRACE : 0) | GLOB_ONLYDIR)) {
>     599|                 $resolvedDirs = array_merge($resolvedDirs, array_map([$this, 'normalizeDir'], $glob));
>     600|             } else {
>   > 601|                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
>     602|             }
>     603|         }
>     604|
>     605|         $this->dirs = array_merge($this->dirs, $resolvedDirs);
> 
>   Exception trace:
> 
>   1   Symfony\Component\Finder\Finder::in()
>       C:\wamp\www\SPF\vendor\laravel\framework\src\Illuminate\Foundation\Console\ViewCacheCommand.php:67
> 
>   2   Illuminate\Foundation\Console\ViewCacheCommand::bladeFilesIn()
>       C:\wamp\www\SPF\vendor\laravel\framework\src\Illuminate\Foundation\Console\ViewCacheCommand.php:36

I have Laravel 6.0.2 and pragmarx/tracker: 3.4.1
I don't use this package views because I've created my own views maybe that is the reason I get this error but I don't know how to work around this in my situation.
thanks

**Comment by tornadofay** [comment]
> I'm sorry to reopen this but i still have this error
> 
> > C:\wamp\www\SPF>php artisan view:cache
> > Compiled views cleared!
> > Symfony\Component\Finder\Exception\DirectoryNotFoundException  : The "C:\wamp\www\SPF\vendor\pragmarx\datatables\src\Bllim\Datatables/views" directory does not exist.
> > at C:\wamp\www\SPF\vendor\symfony\finder\Finder.php:601
> > 597|                 $resolvedDirs[] = $this->normalizeDir($dir);
> > 598|             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? GLOB_BRACE : 0) | GLOB_ONLYDIR)) {
> > 599|                 $resolvedDirs = array_merge($resolvedDirs, array_map([$this, 'normalizeDir'], $glob));
> > 600|             } else {
> > > 601|                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
> > > 602|             }
> > > 603|         }
> > > 604|
> > > 605|         $this->dirs = array_merge($this->dirs, $resolvedDirs);
> > 
> > 
> > Exception trace:
> > 1   Symfony\Component\Finder\Finder::in()
> > C:\wamp\www\SPF\vendor\laravel\framework\src\Illuminate\Foundation\Console\ViewCacheCommand.php:67
> > 2   Illuminate\Foundation\Console\ViewCacheCommand::bladeFilesIn()
> > C:\wamp\www\SPF\vendor\laravel\framework\src\Illuminate\Foundation\Console\ViewCacheCommand.php:36
> 
> I have Laravel 6.0.2 and pragmarx/tracker: 3.4.1
> I don't use this package views because I've created my own views maybe that is the reason I get this error but I don't know how to work around this in my situation.
> thanks

I Solved this problem by creating folder name:[views] in this path :[\vendor\pragmarx\datatables\src\Bllim\Datatables**\views**]

**Comment by davoc** [comment]
Just had this issue and creating directory `\vendor\pragmarx\datatables\src\Bllim\Datatables\views` solved it for me
